### ISSUE TITLE
Elastic support for aioredis 

### ISSUE THREAD

**Issue by ajay1mg** [elastic/apm-agent-python#1080]
**Is your feature request related to a problem? Please describe.**
I am using aioredis in my asyncio based application. aioredis is supported by a similar observability platform like newrelic. Now that I have integrated my app with the aioredis library I don't see the logs instrumentation for it.

**Describe the solution you'd like**
Similar to aiopg and asyncpg, there should be instrumentation for aioredis as well

**Describe alternatives you've considered**
N/A

**Additional context**
async libraries are getting much popularity and these should be added for a popular apm solution like elastic.

**Comment by Sparkycz** [comment]
@rafalstapinski was a little faster than me and opened a PR https://github.com/elastic/apm-agent-python/pull/1081 otherwise my commit is ready to process https://github.com/Sparkycz/apm-agent-python/commit/aa6d61a1cc5fcade54d7546a9981a50ca8dc4164 . However, I'm gonna wait on Rafal if he'll finish his PR.. ;-)

**Comment by Sparkycz** [comment]
Rafal had closed his PR therefore I opened my one..
