### ISSUE TITLE
trace.id is not available in fastapi exception handler

### ISSUE THREAD

**Issue by realabja** [elastic/apm-agent-python#1110]
**Describe the bug**: We have fastapi framework, and we add apm_client for starlette to the application, we want to generate trace.id to correlate logs when an exception happens. I have structlog package for the logging and import `elasticapm.handlers.structlog.structlog_processor`. We set exception handlers in fastapi application for our excpected handlers and also one for `Exception` class to capture the ones that we do not expect. I can get trace.id in child exceptions but not in the exception handler that is comparing to root. 

My goal was to have log Exception types and have log correlation in them.

I am not sure if it is bug or feature request🤷‍♂️
**To Reproduce**

1. create apm agent and fastapi app, add the apm agent to application
```
from fastapi import FastAPI
from elasticapm.contrib.starlette import make_apm_client
from elasticapm.contrib.starlette import ElasticAPM
apm = make_apm_client(config=config)
app = FastAPI()
app.add_middleware(ElasticAPM, client=apm)
```
2. configure structlog
```
import structlog
from elasticapm.handlers.structlog import structlog_processor
def processor(logger, level, log_dict):
    return json.dumps(log_dict)

structlog.configure(processors=[structlog_processor, processor])

```
3. create an child exceptions and root and child exception
```
class AuthException(Exception):
    def __ini__(self):
        super().__init__()


@app.exception_handler(Exception)
async def fallback_handler(request , exc: Exception):
    getLogger().info("Uncaught exception during request handling happend")
    return JSONResponse({"detail": "ROOT EXCEPTION"}, status_code=500)

@app.exception_handler(AuthException)
async def validation_exception_handler(request, exc: AuthException):
    getLogger().info(f"Request Validation exception happend{sys.exc_info()}")
    return JSONResponse({"detail": "CHILD EXCEPTION"}, status_code=404)
```
4. create an endpoint to send request to see if logging formatter/processor works or not
```
@app.post("/")
async def post(body: Any = Body(...)):
    if body == 1: raise AuthException("child exception")
    if body == 2: raise ZeroDivisionError("root exception")
    return JSONResponse({"Response": "test SUCCESS"}, status_code=200)
```
**Environment (please complete the following information)**
- OS: Win and Linux 
- Python version: 3.7
- Framework and version [e.g. Django 2.1]: fastapi 0.63
- APM Server version: _ 
- Agent version: 6.*

**Comment by Sparkycz** [comment]
Generally, the problem is ordering the middlewares in Starlette.
https://github.com/encode/starlette/blob/master/starlette/applications.py#L83

ElasticAPM middleware is a "user middleware". The middlewares in Starlette are like wrappers over wrappers.

the ordering by response/exception processing is:

0. Endpoint method controlled by decorators `@app.post(..)`, `@app.get(..)`,..
1. `ExceptionMiddleware` controlled by `exception_handler` decorator where the argument is not `Exception`
2. User middlewares (e.g. ElasticAPM middleware)
3. `ServerErrorMiddleware` controlled by `exception_handler(Exception)` decorator (argument must be `Exception` or `500`)

In the ordering above, you can see that ElasticAPM is under the ExceptionMiddleware. The ExceptionMiddleware overwrites the raised exceptions to `JSONResponse` (in your case) and the tracking information of the exception under is lost.

It might not be easy to fix the problem in this project, it may be easier to add a constructor argument to overwrite `ExceptionMiddleware` and `ServerErrorMiddleware` or define own the middleware ordering in Starlette.

**Comment by realabja** [comment]
@magichair I wrote a wrapper on the router from fastapi to capture exception and do all apm stuff get trace id and transaction manuelly then reraise exception. Not the cleanest way but it works.

**Comment by basepi** [comment]
I'm not certain that this is a middleware-ordering issue. Because when the request starts, our middleware will get called, and start the transaction. Later, yes, the exception handling middleware will happen before ours, but the exception should still be active in the execution context. So when we fetch the transaction [here](https://github.com/elastic/apm-agent-python/blob/2ec8864597eace4a720ea4711521dc3a12d63f6e/elasticapm/handlers/structlog.py#L54) it should be there, but apparently is not for some reason.

Some more investigation is in order. Sorry for the slow response here.

**Comment by marcoaleixo** [comment]
Hey team!
Do we have any way to handle this?
This occurs with Django as well!

**Comment by basepi** [comment]
@marcoaleixo I haven't dug deep into this issue but I'm expecting the fix to be fairly FastAPI-specific. Would you mind opening a new issue for Django with some details?

**Comment by magichair** [comment]
@basepi any chance this could get picked up for next release? We're really struggling with this, as yes, there is trace.id in our ECS logs for almost everything except the really important logs that happen during the Starlette exception handling. So when we query in our logging for a particular trace.id it all looks ok, when there are clearly other errors occurring that are missing the trace. My team members are looking at adding, yet another distributed trace header into the mix - https://github.com/tomwojcik/starlette-context to remediate this.

**Comment by basepi** [comment]
@magichair I'm not sure how we missed this in our 8.6 planning, but I'm going to take a look. :)

**Comment by magichair** [comment]
(I think) I found the root cause of our troubles. It mostly stems from:
https://github.com/tiangolo/fastapi/blob/0.85.1/fastapi/applications.py#L156-L160
Here, FastAPI is building the middleware. It actually harkens back to my previous attempt at manipulating this (I just did it in the wrong order), https://github.com/elastic/apm-agent-python/issues/1110#issuecomment-938125906

The catch-all FastAPI exception handler that we register
```python
app.exception_handler(Exception)(uncaught_exception_handler)
```
is getting "special cased" and pulled out of the list of `exception_handlers` and instead becomes the `error_handler` for the overarching `ServerErrorMiddleware`.
https://github.com/tiangolo/fastapi/blob/0.85.1/fastapi/applications.py#L162-L168
The `self.user_middleware` is where ElasticAPM ends up and as such, finishes and does all of its `finally` work like `end_transaction()` before the `ServerErrorMiddleware` kicks in and does its work.

**Comment by basepi** [comment]
@magichair Great research, thank you.

Perhaps we need to instrument `ServerErrorMiddleware` to make sure the transaction is available at that point. I'll have to think on this and dive the code a bit.

**Comment by basepi** [comment]
It appears that both Starlette and FastAPI automatically use `ServerErrorMiddleware` as the outer-most middleware. However, only FastAPI monkeys with the `Exception` handling. One potential solution is to monkeypatch that middleware class to do our `end_transaction()` there, instead of in the user middleware. But that's a bit more brittle than what we're doing now since we'd be reaching into their code instead of sticking to our middleware.

It still may be the best option. It would be a really simple wrapper and I don't know how to send the transaction context forward otherwise. 🤔

**Comment by basepi** [comment]
Just kidding, Starlette does it too so this will be good to get fixed: https://github.com/encode/starlette/blob/3453fd6b6259393f3744815b49af297c934f32d0/starlette/applications.py#L85-L99

**Comment by basepi** [comment]
I have a POC in #1674 but it's not working yet. My code isn't being hit, still trying to figure out why.

**Comment by magichair** [comment]
Now that's the APM monkeypatching magic I was looking for! Here I am mitigating over in user land 😛 
Thank you for jumping in on this, I'm happy to help test in any way I can.
