### ISSUE TITLE
APM Server returns "validation error: error: 'parent_id' required when 'transaction_id' is set"

### ISSUE THREAD

**Issue by NielkS** [elastic/apm-agent-python#1415]
**Describe the bug**: APM Server returns an error when parent_id is not set

**To Reproduce**
N/A

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux
- Python version: 3.6
- Framework and version [e.g. Django 2.1]: django 3.2.5
- APM Server version: 7.14.1
- Agent version: 6.3.3

**Additional context**
Found https://github.com/elastic/apm-agent-python/pull/307 implemented some time ago - what was the reason for implementing this ? With latest APM server, my understanding is that when `transaction_id` field is set, then `parent_id` field is required as well: https://github.com/elastic/apm-server/blob/v7.14.2/docs/spec/v2/error.json#L1025

**Comment by beniwohli** [comment]
Hi @NielkS. There seems to be some confusion here. #307 deals with transactions, not errors, but the JSONSchema you linked to is about errors. For transactions, there is no such dependency between `transaction_id` and `parent_id` as far as I can tell.

For errors, we set the distributed tracing IDs here: https://github.com/elastic/apm-agent-python/blob/8b18ddc91e30d131c64754864932fb92bcb69ef8/elasticapm/base.py#L544-L549

`parent_id` is a bit of a special case, because we have to set it to the current `span_id` if an exception happens inside a span. This happens here: https://github.com/elastic/apm-agent-python/blob/8b18ddc91e30d131c64754864932fb92bcb69ef8/elasticapm/traces.py#L904-L909

and here: https://github.com/elastic/apm-agent-python/blob/8b18ddc91e30d131c64754864932fb92bcb69ef8/elasticapm/events.py#L146-L147

As I currently understand it, the validation error that you see can only happen if we somehow set `parent_id` to `None`, which would happen if `span.id` was `None`, but I don't see how that could happen...

**Comment by NielkS** [comment]
Thanks @beniwohli for the clarifications - I confused transaction and error schemas, indeed.

> (...) which would happen if span.id was None, but I don't see how that could happen...

Ah, forgot to mention that, but the initial error comes from a worker thread - you may remember https://github.com/elastic/apm-agent-python/issues/499 (basically replace the print statement with logger.error in your example)

```
from concurrent.futures import Future, ThreadPoolExecutor
from elasticapm.traces import execution_context
from typing import Any, Callable
import logging

executor = ThreadPoolExecutor(max_workers=10)

def _apm_wrapper(func: Callable) -> Callable:
    apm_transaction = execution_context.get_transaction()
    apm_span = execution_context.get_span()

    def inner(*args):
        execution_context.set_transaction(apm_transaction)
        execution_context.set_span(apm_span)
        return func(*args)

    return inner

def work_parallel(list[tuple[Callable, list[Any]] todo):
    for func, args in todo:
        wrapped= _apm_wrapper(func)
        executor.submit(wrapped, *args)
    # ....

work_parallel([(lambda: logging.error("no parent_id :-("), []),])
```

I don't know if that's relevant, but in my usecase, this `work_parallel` call is started from within a celery task, so the 'elasticapm.contrib.django.middleware.TracingMiddleware' middleware is not called before the `logging.error` line runs.

**Comment by basepi** [comment]
Sorry we haven't been more attentive here -- are you still running into this issue? Can you clarify your custom code a bit? It seems like you're doing some odd things (interacting with execution_context directly), rather than sticking to the public API and that might be causing your issues.

**Comment by kalemas** [comment]
Hi, not sure it my issue is relative to this one, but i getting same warning when submitting some messages, debgging i found following:
![image](https://user-images.githubusercontent.com/638393/201439659-012bdd5c-1b46-4304-af03-8175ddac246b.png)
at 
![image](https://user-images.githubusercontent.com/638393/201439751-6cee0a81-0115-44d0-91ee-82b7b36c7419.png)

but i have no clue of why there is dropped span, current transaction should not sample spans in this environment:
![image](https://user-images.githubusercontent.com/638393/201439995-2e559d97-b5c9-4142-96b1-6f514f2f9100.png)

heh, it seem because of i use `elasticapm.capture_span(leaf=True)`, have no clue if that is supposed to be so.

**Comment by basepi** [comment]
If a span is marked as `leaf=True`, child spans will be dropped. This is to hide irrelevant spans from underlying transport libraries, etc. You see the `elasticsearch` span, for example, not the underlying http call.

@kalemas I think a new issue is likely warranted, I think we'll need more context around what you're doing to solve this issue.
