### ISSUE TITLE
Test failure in main branch possibly with jinja2 import

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-python#1502]
We have detected the following test failure:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/main/27/pipeline/185

Seems as the return code may be coming from this line:

`[2022-03-24T15:09:10.160Z] make: *** [Makefile:14: test] Error 5`

There is a warning about a jinja import, but it's not clear whether or not it's the true cause of this issue:

```
[](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/main/27/pipeline/185#step-1454-log-174)[](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/main/27/pipeline/185#step-1454-log-175)[](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/main/27/pipeline/185#step-1454-log-176)[2022-03-24T15:09:09.899Z] =============================== warnings summary ===============================

[2022-03-24T15:09:09.899Z] tests/instrumentation/jinja2_tests/jinja2_tests.py:42
[2022-03-24T15:09:09.899Z]   /app/tests/instrumentation/jinja2_tests/jinja2_tests.py:42: PytestUnknownMarkWarning: Unknown pytest.mark.jinja2 - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html[](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/main/27/pipeline/185#step-1454-log-177)
[2022-03-24T15:09:09.899Z]     pytestmark = [pytest.mark.jinja2]
```

Could somebody please investigate this failure? Thanks.

**Comment by beniwohli** [comment]
Hey @cachedout! I'm already investigating this. The jinja2 bit is not really relevant. The direct cause of the test failure is that no actual test is run (all tests are skipped for some reason). Our test matrix setup uses [`pytest.importorskip`](https://docs.pytest.org/en/6.2.x/reference.html#pytest-importorskip) to select/skip tests depending on which modules are installed (e.g. MySQL tests are automatically skipped if no mysql module is available, which is the case for all test runs except for the mysql-specific ones).

The problem with this is that an import could also fail due to reasons other than the module missing, and `importorskip` doesn't differentiate between those and just silently suppresses them. So there's probably some import error happening when trying to import flask.

**Comment by cachedout** [comment]
@beniwohli Many thanks as always for the quick and through response. Makes perfect sense.
