### ISSUE TITLE
unexpected keyword argument 'flushed' in lambda extension

### ISSUE THREAD

**Issue by josef-cech-acc** [elastic/apm-agent-python#1627]
**Describe the bug**: 
Call self.send(data,flushed=true) in https://github.com/elastic/apm-agent-python/blob/main/elasticapm/transport/base.py#L183 uses not declared argument.

**To Reproduce**

1. we use elastic-apm-extension-ver-1-0-0-x86_64 as lambda layer 
2. use a newer version of elastic-apm=">6.8.1"
3. Result : TypeError: send() got an unexpected keyword argument 'flushed'

**Environment (please complete the following information)**
- OS: N/A - use lambda
- Python version: any
- Framework and version [e.g. Django 2.1]: None
- APM Server version: 1.0.0
- Agent version: >6.8.1

**Comment by basepi** [comment]
Some clarification might be needed.

The `flushed=True` behavior was introduced in 6.9.0, so that might be your issue if you're using 6.8.1. It's also not designed to be called directly, we call it via [this line](https://github.com/elastic/apm-agent-python/blob/45abe9734dd25acdc21633cdc58ab80304506d8a/elasticapm/contrib/serverless/aws.py#L224).

Are you using our [official lambda integration](https://www.elastic.co/guide/en/apm/agent/python/current/lambda-support.html) and extension?

**Comment by josef-cech-acc** [comment]
We upgrade quite recently ( last week) - our team which takes care of APM did some upgrades on the server side as well and after that change, we experienced a heavy raise in this issue in our logs. I don't know why but I don't experience any issue since I downgrade elastic-apm to 6.8.1. All my point is that signature is required  "forced_flush" but call "flushed" argument on that specific line -  https://github.com/elastic/apm-agent-python/blob/main/elasticapm/transport/base.py#L183

**Comment by basepi** [comment]
Huh. You're totally right. I'm actually not sure how my manual testing didn't catch this. I'll have a fix shortly, thanks for the report.
