### ISSUE TITLE
Instrument psycopg3

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-agent-python#1789]
psycopg3 was released some time ago. We currently only support psycopg2. While psycopg3 is quite similar from psycopg2, the differences are large enough to probably require its own instrumentation (e.g., extensions are gone in psycopg3 AFAICT).

Also, there is an asyncio interface in psycopg3, which requires its own instrumentation.

https://www.psycopg.org/psycopg3/docs/index.html
https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html

**Comment by gianfrancodemarco** [comment]
Hello, is there an approximate release date for this?

**Comment by basepi** [comment]
We don't currently have a release date. It's good to know someone is in need of this instrumentation, it helps us prioritize!

**Comment by airscripts** [comment]
It would be useful also for us.

**Comment by mariocandela** [comment]
+1

**Comment by minhtule** [comment]
Hi @basepi @beniwohli! We're using Django (synchronous mode) and would love to upgrade to Psycopg3. Is there anything I could do to speed up the Elastic APM support for Psycopg3? I could open a PR adding support for Psycopg3 synchronous operations which is pretty much similar to Psycopg2, adopting [`Psycopg2Instrumentation`](https://github.com/elastic/apm-agent-python/blob/main/elasticapm/instrumentation/packages/psycopg2.py#L77) class.

**Comment by basepi** [comment]
@minhtule that would be a welcome contribution! I assumed this would be pretty easy work, we just haven't gotten to it yet.

**Comment by mariocandela** [comment]
Hi @minhtule, we need it too as a team, if you haven't started yet we can do it! otherwise tell me how we can help you ❤️

**Comment by minhtule** [comment]
I checked the 4 methods that [`Psycopg2ExtensionsInstrumentation`](https://github.com/minhtule/apm-agent-python/blob/35acac150833e5b451a82a276d892dd6f6c75c28/elasticapm/instrumentation/packages/psycopg2.py#L113-L117) instruments for Psycopg2 and it doesn't seem like we need something like that for Psycopg3.
- [`psycopg2.extensions.encrypt_password()`](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.encrypt_password) is equivalent to [`psycopg.pq.PGconn.encrypt_password()`](https://www.psycopg.org/psycopg3/docs/api/pq.html#psycopg.pq.PGconn.encrypt_password). Because this `PGconn` instance can be accessed as a property of [`psycopg.Connection`](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.pgconn), we don't seem to have the problem as in Psycopg2 where the proxy connection doesn't work in `psycopg2.extensions`.
- [`psycopg2.extensions.quote_ident()`](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.quote_ident)  doesn't seem to have an equivalent in Psycopg3.
- [`psycopg2.extensions.register_type()`](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.register_type) and [`psycopg2._json.register_json()`](https://www.psycopg.org/docs/extras.html#psycopg2.extras.register_json) doesn't exist in Psycopg3 which uses [server-side binding](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding) and has a completely different [data adaptation system](https://www.psycopg.org/psycopg3/docs/advanced/adapt.html). I tested the [custom adapter example](https://www.psycopg.org/psycopg3/docs/advanced/adapt.html#writing-a-custom-adapter-xml) and there wasn't any issue with the proxy connection/cursor.
