### ISSUE TITLE
Add support for documented capture_body config to aiohttp requests

### ISSUE THREAD

**Issue by stj** [elastic/apm-agent-python#1881]
**Describe the bug**: Capturing requests bodies of aiohttp requests is currently not implemented. Though the documentation gives the impression all supported frameworks do support the `capture_body` configuration.

**To Reproduce**

1. Set `capture_body` to `all`
2. Instrument aiohttp
3. Make a request with body to any URL
4. Look for `body` in APM trace

**Environment (please complete the following information)**
- Framework and version [e.g. Django 2.1]: aiohttp

**Additional context**

n/a

**Comment by basepi** [comment]
@nbarbey Opened a [PR](https://github.com/elastic/apm-agent-python/pull/1892) for this. They are new to the code base, and so I was looking for an example in the codebase from which they could model their changes.

I realized that I didn't think about this issue enough. We don't typically collect the body of requests from client libraries. This is because the expectation is that the server will collect the body and is also instrumented. So, we collect the bodies in server frameworks such as Django, Flask, and Starlette. But we don't collect the body from client libraries like `requests` or `urllib3`.

I'm considering closing this as a "won't fix", but I'd be interested to hear more about your needs, @stj.

**Comment by stj** [comment]
While the server might collect the body, it might be a server owned by a different party that does not give access to apm data.

My goal is to track the request body send to a server not under my control. If there is an error response from that server I have data on what the body was and can replicate the error. This will help find a bug in the body or have information that I can take to the owner of the receiving server and fill a bug report.

I actually thought that the instrumentation of the `elasticsearch` python client does honor the `capture_body` setting since it does [capture client request bodies](https://github.com/elastic/apm-agent-python/blob/7eadd285f698fe918618e329003294a19b88db8a/elasticapm/instrumentation/packages/elasticsearch.py#L97). Though I now see that it does not use the `capture_body` config to control that behavior.

The documentation of `capture_body` doesn't mention that it is restricted to a server and not used for client library instrumentation. Can we make the documentation point this out?

Thinking about this a bit more, it might be that I don't want to capture bodies of all client requests and only requests to specific URL/domains. If you do consider adding this feature than I'd be interested in having more than an on/off switch for it.

**Comment by basepi** [comment]
Makes sense. That's why the `elasticsearch` client instrumentation does capture the body, because typically the server will not be instrumented (though that's changing).

It's an interesting case, but I think maybe this is a place where it should rely on user-enrichment. Perhaps via the `elasticapm.set_span_context()` that I added here: https://github.com/elastic/apm-agent-python/pull/1893

For now, I'm going to close this. If user-enrichment doesn't fit your case, perhaps we can revisit a broader solution across our client instrumentations.
