### ISSUE TITLE
Fix issue labeler workflow

### ISSUE THREAD

**Issue by xrmx** [elastic/apm-agent-python#2001]
**Describe the bug**: 

Update labeler workflow to use the correct actions and groups, see nodejs changes:
https://github.com/elastic/apm-agent-nodejs/pull/3906/files

**To Reproduce**

1. Open an issue as @xrmx 
2. Issues labeled as community

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version:
- Framework and version [e.g. Django 2.1]:
- APM Server version:
- Agent version:

**Additional context**

None

**Comment by trentm** [comment]
There was an error in #2003. The labeler workflow is failing: https://github.com/elastic/apm-agent-python/actions/workflows/labeler.yml with:

```
 Invalid workflow file: .github/workflows/labeler.yml#L32
The workflow is not valid. .github/workflows/labeler.yml (Line: 32, Col: 11): A sequence was not expected
```

Instead of:
https://github.com/elastic/apm-agent-python/blob/adff59cb29214f661b3569725aafb1a670d986a9/.github/workflows/labeler.yml#L31-L33
it wants this:
https://github.com/elastic/apm-agent-nodejs/blob/f0b6a098db63ba7e21d7ab3febf3d739315746c8/.github/workflows/labeler.yml#L38-L40
