### ISSUE TITLE
Possible memory-leak

### ISSUE THREAD

**Issue by alexanderad** [elastic/apm-agent-python#234]
We are running 2 flask apps serving APIs for two separate projects.
Last two days we started getting alerts from monitoring systems on high memory usage on nodes running these apps.

We spent some time reviewing shared components and recent changes for potential cause until the only one left was `elastic-apm` module. API for one of the apps is normally running on 3 nodes and the traffic is load balanced via Amazon's Application Load Balancer, so every node receives a fair share. We disabled APM via the config on one of nodes and restarted gunicorns on all three. After 48 hours running we see the following:

* app-01 node without elastic-apm: 3.4% to 5.4% node memory usage (across multiple gunicorn processes)
* app-02 node with elastic-apm: 12.9% ... 16.6% memory usage
* app-03 node with elastic-apm: 11.6% ... 18.9% memory usage

In absolute numbers, it is ~200Mb on app-01 vs 600-700Mb on 02 and 03.
All 3 nodes are brought up with orchestration tools, so identical in hardware and software and serve identical workload.

Due to the nature of the API, on weekends we do have quite low usage, which probably explains why after 48 hours we don't yet have alerts firing.

Versions installed:
```python
Description:	Ubuntu 16.04.3 LTS

Flask==0.10.1
elastic-apm==2.1.1
gunicorn==19.4.1
```

Initialization:
```python
    app = Flask(__name__, ...)
    ...
    # elastic apm
    app.apm = None
    if app.config.get('elastic', {}).get('service_name'):
        from elasticapm.contrib.flask import ElasticAPM
        app.apm = ElasticAPM(app, **app.config['elastic'])
```

Config:
```
[elastic]
service_name = "Production Application API"
server_url = "{{ .Data.server_url }}"
secret_token = "{{ .Data.secret_token }}"
environment = "production"
```

Please suggest how we can help investigating this issue. Thanks!

**Comment by beniwohli** [comment]
Thanks for the report @alexanderad, and sorry for the long answer time, I was under the weather for a few days 🤒

Some overhead is to be expected when using Elastic APM, but I agree that ~400MByte seems excessive. 

One possible source for this could be internal caches that we use. The one with the largest impact is our source line cache, which is used when generating stack traces for errors and spans. Instead of reading the source file every time (which would cause a lot of I/O and be quite slow), we cache the result of the read:

https://github.com/elastic/apm-agent-python/blob/c8ae9e451ce216aac04cac477fd62d35f8ea98ef/elasticapm/utils/stacks.py#L30-L31

Could you try to disable capturing of stack traces for spans on one of your app servers and see if that helps? You can do that by setting [`span_frames_min_duration`](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-span-frames-min-duration-ms) to `0`.

**Comment by beniwohli** [comment]
@alexanderad good to hear that you found a workaround. I'm closing this for now, as I wasn't able to reproduce a memory leak.
