### ISSUE TITLE
Add support for Metrics / Stats API

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-python#245]
Work is underway to add support for Metrics to the API/server: https://github.com/elastic/apm-server/issues/964
Support needs to be added to this agent too.
The default minimum set of metrics should be supported. TBD which additional metrics will be supported for this agent.

**Comment by beniwohli** [comment]
Turns out that gathering most of these metrics is relatively difficult with vanilla Python and a platform independent way, but would get pretty trivial if we depended on `psutil`:

Metric Name | psutil
-- | --
system.cpu.total.norm.pct | `psutil.cpu_percent()`
system.memory.total | `psutil.virtual_memory().total`
system.memory.actual.free | `psutil.virtual_memory().available`
system.process.cpu.total.norm.pct | `psutil.Process.cpu_percent() / psutil.cpu_count()`
system.process.memory.size | `psutil.Process.memory_info().vms`
system.process.memory.rss.bytes | `psutil.Process.memory_info().rss`

Unfortunately, psutil requires GCC to be installable on Linux and OSX (binary wheels are currently only provided for Windows).

I suggest to add a "system-metrics" `extra` dependency with psutil. If psutil isn't installed, the system metrics wouldn't be set. Later on, we can add these metrics e.g. by reading `/proc/stat` et al on Linux, and similar methods on OSX/Windows.

@graphaelli @roncohen @axw thoughts?

**Comment by axw** [comment]
psutil looks good, and seems like a reasonable first step if you're planning to use it for Windows anyway. I wouldn't rely on it on Linux for long, though. On Windows you could probably later just use ctypes to access the psapi.dll functions, but maybe it doesn't matter if binary wheels are easy on Windows. I don't think it's worth doing anything else for macOS.

I just took a quick look, and on Linux it appears to be calculating the CPU usage a little differently to how the Go agent and Beats does. Beats calculates the usage based on non-idle time, where idle time is idle+iowait. Psutil is calculating the usage based on system+user time, which IIANM does not capture a few of the Linux-specific times.

I'm not sure how much of a difference it'll make, but when you implement `/proc/pid/stat` reading, it would be good to align on that.
