### ISSUE TITLE
docs: drop-in support for other WSGI-compatible applications

### ISSUE THREAD

**Issue by bobheadxi** [elastic/apm-agent-python#272]
On the README, it's noted that:

> Elastic APM also includes drop-in support for any WSGI-compatible web application.

I can't seem to find any documentation/existing issues pertaining to how exactly this is done - any help here would be appreciated. If it helps, the framework in question is [Pylons/pyramid](https://github.com/Pylons/pyramid), which shows up on the [official WSGI list](https://wsgi.readthedocs.io/en/latest/frameworks.html)

Thanks!

**Comment by beniwohli** [comment]
Hi @bobheadxi. Sorry for the late reply. Unfortunately, that is some old text from when the agent only captured exceptions and not APM data. I'll update the text. The instrumentation needed for APM is much more framework specific, that's why so far we only have official support for Django and Flask.

The good news is that I recently wrote a blog post on how to write a custom framework integration, using Pyramid as an example. You can find it here: https://www.elastic.co/blog/creating-custom-framework-integrations-with-the-elastic-apm-python-agent, and the integration module is here: https://github.com/beniwohli/pyramid-elasticapm-demo/blob/master/app/elasticapm_integration.py

Let me know if that works for you :)

**Comment by bobheadxi** [comment]
Thanks a lot @beniwohli - this seems like exactly what I was looking for.
