### ISSUE TITLE
Include authorization http header in mask fields 

### ISSUE THREAD

**Issue by naviens** [elastic/apm-agent-python#274]
In REST based token authentication `auth token` was sent via http `authorization ` which need to be masked.

**Comment by beniwohli** [comment]
Hi @naviens! Excellent point, and sort of embarrassing that we didn't have it in the [default sanitization list](https://github.com/elastic/apm-agent-python/blob/e21b306da70995ca1582666378b7059495ff1bee/elasticapm/processors.py#L20) since forever. I'll add it ASAP.

Ideally, we should probably make this list extendable via configuration, but that can wait for a later release.
