### ISSUE TITLE
Create plugin to Tornado framework

### ISSUE THREAD

**Issue by laerteallan** [elastic/apm-agent-python#297]
Hi,

I  developed this plugin to tornado framework and would like of the shared with you.  And you interested with this plugin? 

Regards,
Laerte Allan

**Comment by beniwohli** [comment]
Hi @laerteallan. Sorry for the long reply time. Support for Tornado would be very interesting. Feel free to open a pull request so we can discuss it further there.

However, we don't fully support asyncio and other asynchronous event loops just yet. There is a pull request that adds some support (#252), but due to some higher priority tasks, it is somewhat dormant. I hope to pick up work on it soon again.

**Comment by laerteallan** [comment]
Hi @beniwohli I will open pull requests with the unittest. 

thanks very good by ansewer.

**Comment by tomershaul2** [comment]
Hi! Is there any progress with the tornado pull requests? Seems like a very useful feature! A lot of people will be very happy to use it!

**Comment by beniwohli** [comment]
@tomershaul2 There is a PR by @laerteallan here: https://github.com/elastic/apm-agent-python/pull/323

Unfortunately, I currently don't have the bandwidth to take a closer look at the pull request. If you have time to give it a try, that would be super helpful!

**Comment by basepi** [comment]
We have Tornado 6.0+ support as of [v5.4.0](https://github.com/elastic/apm-agent-python/releases/tag/v5.4.0)!
