### ISSUE TITLE
APM agent kills UWSGI with signal 6

### ISSUE THREAD

**Issue by davyngugi** [elastic/apm-agent-python#340]
We have a Django project served by nginx and uwsgi on Python 2.7.6. We have observed that with elastic-apm installed and configured appropriately in the settings, UWSGI keeps getting killed with:
`DAMN ! worker 4 (pid: 7751) died, killed by signal 6 :( trying respawn ...`

Consequently, the error `Fatal Python error: Couldn't create autoTLSkey mapping` seems to appear intermittently before the crash.

UWSGI has threading enabled as suggested in [here](https://www.elastic.co/guide/en/apm/agent/python/current/django-support.html)
```
[uwsgi]
...
# maximum number of worker processes
processes = 4 

# Threads per process
enable-threads = true
threads = 2
...
```

Here is the error message
```
Fatal Python error: Couldn't create autoTLSkey mapping
DAMN ! worker 4 (pid: 7764) died, killed by signal 6 :( trying respawn ...
Respawned uWSGI worker 4 (new pid: 7772)
```

**Comment by beniwohli** [comment]
Hi @davyngugi 

searching for that error message, it seems that this could be caused by a memory limit that is too low, see e.g. https://stackoverflow.com/questions/18638518/fatal-python-error-couldnt-create-autotlskey-mapping-with-c-binding/24738743. My guess is that you are already running relatively close to the memory limit, and using the APM agent adds enough memory overhead to get you over the limit. Can you try to increase the limits as outlined in the answer on that StackOverflow question?

BTW, I highly recommend to upgrade your Python version to a newer version (the newest in the 2.7 branch is 2.7.13). 2.7.6 is 5 years old and has quite a few security issues (like the lack of SSL certificate validation).

**Comment by beniwohli** [comment]
I'll close this for now. @davyngugi feel free to re-open if this continues to be an issue with increased memory.
