### ISSUE TITLE
Tracking enhacements for `Elasticsearch.search`

### ISSUE THREAD

**Issue by HonzaKral** [elastic/apm-agent-python#354]
Currently in https://github.com/elastic/apm-agent-python/blob/master/elasticapm/instrumentation/packages/elasticsearch.py#L47 we are discarding everything but the `query` in the body which can cover some very important (from a performance point of view) aspects of the operation for example pagination - large `from`/`size` can have severe impact - and aggregations - if present can severely impact everything.

It would also be great to track the statistics on the response:

`took`, `hits.total`, `_shards.total/failed/successful` information

which can expose badly structured code/queries or performance issues in elasticsearch

Thank you!

**Comment by basepi** [comment]
@HonzaKral (or @sethmlarson) can you clarify why including `aggs` can be problematic for collecting the query? I recently "fixed" this in #940 because a user was complaining about the lack of `aggs` which were the important part of the query for his debugging.

For the additional information we could collect, I'm not sure where we would put it. We currently don't populate any custom context ourselves, we leave that for the user. We also don't collect service-specific data like this for anything else we instrument.

Unless @beniwohli has any bright ideas I think I'm going to probably close this issue (once we resolve the above question about `aggs` and other query data).

**Comment by HonzaKral** [comment]
I don't see how including the whole body could be problematic, quite the opposite. The `_search` API is used for many other things besides just running a `query` (aggregations, suggestions, sorting, script fields, pagination, ... ...) all of which can have **significant** impact on performance and behavior and are therefore important to track.

> We also don't collect service-specific data like this for anything else we instrument.

We do provide information for `rows_affected` for SQL for example, this would be similar and would belong in the same place.

**Comment by basepi** [comment]
Ah, I misread your original issue, I thought you were saying that we purposely only include the query because including the whole payload could be problematic. Glad my fix was a good one!

And thank you for pointing out `rows_affected` on the span context. I hadn't actually internalized that spans have their own context, and it doesn't have a standalone spec in the apm server repo. Rather, span context is here: https://github.com/elastic/apm-server/blob/master/docs/spec/spans/span.json

I think `hits.total` could probably go under the existing `rows_affected`, and we could easily add something for `took`. I'm trying to figure out  what field we might use for the `_shards.total/failed/successful` information. Ideally it would be a field other db providers could use for similar context. I'll have to think on this (and we'll need a PR against that spec before we can add these new context pieces).

**Comment by Sparkycz** [comment]
I'm adding `http.status_code` and `db.row_affected` but I can't find relevenant field for `_shards.total/failed/successful` in the APM span specification https://github.com/elastic/apm-server/blob/master/docs/spec/v2/span.json
Could you check the APM span specification and suggest me the field mapping please if exists? 

Guess the field `took`(response time) is not important because span measures it by default from the client side, or?
