### ISSUE TITLE
Django/Celery task not reported if worker is restarting

### ISSUE THREAD

**Issue by courcelm** [elastic/apm-agent-python#404]
**Describe the bug**: 

Apm agent doesn't send the task event when the Django/Celery worker is restarting (child process exiting after exceeding memory limit)

**To Reproduce**

1. Start celery worker with --max-memory-per-child=150000
2. Launch a task that uses more memory than the above threshold
3. Check that the worker is restarting: child process exiting after exceeding memory limit (181000KiB / 150000KiB)
4. No event is found in elasticsearch/kibana

**Expected behavior**: 

Apm should send the event before the worker is restarting.

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux
- Python version: 3.6.7
- Framework and version [e.g. Django 2.1]:  1.11.18
- APM Server version: 6.6
- Agent version: elastic-apm==4.0.3

**Comment by beniwohli** [comment]
Hi @courcelm 

generally speaking, when memory is tight, all bets are off, since the agent might not be able to allocate the necessary memory to process the event. However, in this case, the memory limit should be somewhat soft (as in, not enforced by the operating system, but by celery). I'll have a closer look why the data isn't sent in this specific case.

Also, sorry for the long answer time :(

**Comment by beniwohli** [comment]
Hi @courcelm. This issue should be fixed in the latest version of the agent (4.2.2). I'll close this issue, feel free to re-open if you see it again.
