### ISSUE TITLE
Redis request stack trace

### ISSUE THREAD

**Issue by BrikerMan** [elastic/apm-agent-python#413]
**Is your feature request related to a problem? Please describe.**
Is that possible to add stacktrace to redis access. I just need to know which line of code calls the redis access.
![image](https://user-images.githubusercontent.com/9368907/53069492-256e0d00-3517-11e9-92d4-183e127382ad.png)

**Comment by axw** [comment]
By default, stack traces are only captured for spans that take longer than 5ms. You can configure this: https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-span-frames-min-duration

**Comment by BrikerMan** [comment]
Thanks, solved my problem. Here is another question maybe you could help. Is that possible to add my own modules time cost to the timeline? I want to fill this gap.
![image](https://user-images.githubusercontent.com/9368907/53071166-67e61880-351c-11e9-8054-9803ee1c2ce7.png)

**Comment by axw** [comment]
Yes, you can create your own "spans". See the docs: https://www.elastic.co/guide/en/apm/agent/python/current/instrumenting-custom-code.html.

I'll close this now, since there is no bug. If you have more questions, please ask on the forum: https://discuss.elastic.co/c/apm. Questions are more likely to be seen there by others, and we prefer to reserve GitHub Issues for bugs and feature requests. Thanks!
