### ISSUE TITLE
Exception raised in `set_context()`

### ISSUE THREAD

**Issue by zry656565** [elastic/apm-agent-python#541]
**Describe the bug**: ...

```
[host: noj-59dfd94498-45jdw|pid: 24294|timestamp: 1564716068.956608] [ERROR|elasticapm.errors:188] Exception during timing of request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/elasticapm/contrib/django/middleware/__init__.py", line 185, in process_response
    elasticapm.set_context(lambda: self.client.get_user_info(request), "user")
  File "/usr/local/lib/python3.7/dist-packages/elasticapm/traces.py", line 410, in set_context
    transaction.context[key].update(data)
TypeError: 'function' object is not iterable
```

Related codes:

https://github.com/elastic/apm-agent-python/blob/ae1c777a975c02f02eb12fe8aa9e3a9077168ef1/elasticapm/traces.py#L615-L631

And when I print `data` when meeting exception, the output is:

```
<function TracingMiddleware.process_response.<locals>.<lambda> at 0x7f39e36a00e0>
```

I guess maybe we have to deal with the situation that `data` is callable and `transaction.is_sampled == False`.

**Expected behavior**:

`set_context()` should handle `data` in lambda type well.

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.7.4
- Framework and version:  Django 2.1.9
- APM Server version: -
- Agent version: 4.2.2

**Comment by beniwohli** [comment]
@zry656565 thanks for opening this super detailed issue! I had a look, and as far I can tell, this happens if `set_context()` is called twice in an unsampled transaction, first with a dictionary, then with a callable. Something like this:

https://github.com/elastic/apm-agent-python/blob/187cc2bab109e8a8171471c4033e21a051b2cb1e/tests/instrumentation/transactions_store_tests.py#L424-L434

I opened #542 to address this issue. With that change, we will bail out early in `set_context` if the transaction is not sampled.

**Comment by zry656565** [comment]
Cool, happy to know this. :+1:
