### ISSUE TITLE
value too long for type character varying

### ISSUE THREAD

**Issue by chripede** [elastic/apm-agent-python#573]
**Describe the bug**: When one of the parameters to a psycopg2 query is longer than 255 characters an exception is thrown `value too long for type character varying`

```
StringDataRightTruncation: value too long for type character varying(255)

  File "django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "elasticapm/instrumentation/packages/dbapi2.py", line 204, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "elasticapm/instrumentation/packages/dbapi2.py", line 233, in _trace_sql
    return method(sql, params)
```

**Expected behavior**: Maybe just cut all params off `[:255]`

**Environment (please complete the following information)**
- Python version: 3.6
- Framework and version [e.g. Django 2.1]: Django 2.0
- Agent version: 5.1.0

**Comment by beniwohli** [comment]
@chripede from what I can see, I don't think this is an issue with the Elastic APM agent, but with either your data or data model. Unfortunately, due to the fact that we wrap certain methods of psycopg2, elasticapm code appears in the stack trace, but the exception is triggered in psycopg itself.

I'm closing the issue, feel free to re-open if I misunderstood things.
