### ISSUE TITLE
SQL Alchemy DB Calls APM logging 

### ISSUE THREAD

**Issue by soumithx** [elastic/apm-agent-python#608]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by basepi** [comment]
@soumithx I'm going to close this as a duplicate of #239

**Comment by basepi** [comment]
Er, whoops, I misread my email notifications as #239 being a new issue (while it was actually just a resurrected issue).

Please fill in the template next time, instead of leaving it default.

That said, #239 has a lot of good information on this topic. Basically, we have avoided instrumenting SQL Alchemy directly, instead preferring to instrument the actual provider, such as [pymssql](https://github.com/elastic/apm-agent-python/issues/239#issuecomment-399957481).

Which underlying provider are you using?

**Comment by soumithx** [comment]
@basepi , actually using flask and sqlalchemy , on which file is good to add  apm agent   for db calls

**Comment by basepi** [comment]
You can find information on instrumenting flask here: https://www.elastic.co/guide/en/apm/agent/python/current/flask-support.html

For the sqlalchemy end, what underlying database are you using? sqlalchemy is an SQL abstraction toolkit, not a database in and of itself. For example, in #239 the user was using pymssql underneath.

**Comment by soumithx** [comment]
@basepi ,   seems i am using  cymysql ?

`self.engine = create_engine(f'mysql+cymysql://{self.username}:{self.password}@{self.host}/{self.database}',
                                    poolclass=NullPool)`

**Comment by soumithx** [comment]
its working now ,i can close 

thanks for response

**Comment by basepi** [comment]
Glad you got it working!
