### ISSUE TITLE
Python RQ support

### ISSUE THREAD

**Issue by stlk** [elastic/apm-agent-python#637]
I'm having hard time setting up APM with [Python RQ](http://python-rq.org/). I tried following old solution [Python agent only recording some background tasks](https://discuss.elastic.co/t/python-agent-only-recording-some-background-tasks/149707), which led me to creating custom rq.job. But this solution no longer works. I tried setting `API_REQUEST_SIZE` to `1b` instead of `MAX_QUEUE_SIZE` but that didn't make a change.

I tried to debug where the things go wrong but the code is just advanced for me. I created [minimal Django app](https://github.com/stlk/elastic-rq-demo) with Elastic APM working on the view and my attempt to implement `TracingJob`.

Readme describes how to setup the app and how to replicate my issue. It would be great if someone with understanding of the queue and the transport layer could take a look at it.

**Comment by basepi** [comment]
Thanks for opening an issue for me. I'm going to add this to my list, probably for next week.

**Comment by basepi** [comment]
Finally got back to this.

There are two things that you're missing from [the post you were following](https://discuss.elastic.co/t/python-agent-only-recording-some-background-tasks/149707):

**Need to create the client from scratch**
  
I'm pretty sure this is due to the worker spinning up its own client, which includes background threads for sending the transactions to the APM server. When a new RQ job comes in, it forks to handle that job, so the existing Client object loses all of its support threads. As a result the transaction never is sent. Creating a new Client creates these threads and properly handles the transaction. @beniwohli does that sound right?

Note that spinning up a Client is a non-trivial operation, constituting as much as a millisecond of overhead. Keep this in mind, as with a heavy RQ workload this adds up.

**Need to explicitly close the client**

This was called out in that thread, but it was easy to miss. If you don't explicitly close the client, the forked job ends without waiting for the queue flush in the background thread.

Note that with the addition of the `close()` call, I don't think you actually need the `API_REQUEST_SIZE` setting. The `close()` will flush the queue by itself (it's working in my testing, anyway).

Here's the diff on my `tracing_job.py`:

```diff
--- a/elastic_rq_demo/tracing_job.py
+++ b/elastic_rq_demo/tracing_job.py
@@ -1,12 +1,11 @@
 import elasticapm
-from elasticapm.contrib.django.client import get_client
 from rq.job import Job
 import logging
 logger = logging.getLogger('TracingJob')

 class TracingJob(Job):
     def perform(self):
-        client = get_client()
+        client = elasticapm.Client()
         client.begin_transaction("backgroundjob")
         context = {"args": self.args, "kwargs": self.kwargs}
         logger.info(context)
@@ -19,3 +18,5 @@ class TracingJob(Job):
         except:
             client.capture_exception()
             raise
+        finally:
+            client.close()
```

Anyway, thanks again for your question. I was able to learn a bit myself while investigating this. :)

**Comment by stlk** [comment]
Awesome, I've got it working. Thank you for your help!

**Comment by sandys** [comment]
hi guys,
am a little confused on how to use this in flask - should i use it the way its mentioned in code. 

https://github.com/elastic/apm-agent-python/blob/04f0edab39795ec4e3e304afbf82e29b726f7e45/elasticapm/contrib/rq/__init__.py#L32

because this issue mentions some other way and im not able to get it to work

**Comment by basepi** [comment]
@sandys You'll probably want to check out [the old discuss post](https://discuss.elastic.co/t/python-agent-only-recording-some-background-tasks/149707) that was referenced above. But note that this is not a supported use case, it has some big problems in terms of performance due to sending after each event instead of batching.

**Comment by sandys** [comment]
@basepi well we are looking for full tracing rather than a metric ping. im not entirely sure if this is the right issue for it, or if thats a usecase you are planning to support. 
I would say rq and celery would be in the same bucket for these kind of usecases.

**Comment by basepi** [comment]
We actually support celery today. And I think we do want to support rq eventually we just haven't figured out the right way to do so.

**Comment by basepi** [comment]
(I would open a new issue if I were you. Much cleaner than repurposing a "question" issue)

**Comment by sandys** [comment]
Will do.
I wasn't sure if you guys were ok with opening a new issue with pretty much
the same topic!

Just one quick request though - I have simultaneously been discussing with
rq Devs to add any hooks to support APM.

They have offered to do so here -
https://github.com/rq/rq/issues/1230#issuecomment-612698580

Would you be able to comment on what exactly you need from rq to make
this happen? Especially since you support celery much better.

**Comment by basepi** [comment]
Done. :)
