### ISSUE TITLE
When running a development server in debug, events are not sent until server is shut down

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/apm-agent-python#72]
I don't know if this is intended or not, but when running locally using the builtin runserver in Django, the events seem to not be shipped to the APM server until the runserver process is killed, making for some annoying debugging sessions.

Upon shutting down the development server, it sends everything it has collected up until that point:

```
PID 13776: ElasticAPM is attempting to send 1 pending messages
Waiting up to 10 seconds, press Ctrl-C to quit.
(webshop.env)
# henrik at Henriks-MacBook-Pro.local in ~/Development/webshop on git:SHOP-6355 ● [12:01:47]
→ PID 13776: done, took 0.97 seconds to complete.
```

What I would have expected was for events to be shipped after a certain threshold, given any events was collected.

**Comment by beniwohli** [comment]
Hi @HenrikOssipoff 👋 

Theoretically, we should send transactions every ~60 seconds. But these transactions are only sent if there is actually traffic (essentially, we check on every request if more than 60 seconds passed since the last send - if there is not new request, transactions linger on the queue until the server is shut down). Can you verify that if you continuously send requests to your development server, it sends something up after 60 seconds?

We are trying to replace this with a background thread (see #68), but hit some issues when the background thread isn't shut down correctly. Work is ongoing to fix that.

**Comment by HenrikOssipoff** [comment]
Upon further inspection, it does appear to happen that way. Strange, because earlier this morning I had the server open over a window of about 10 minutes, with frequent transactions, and that didn't log anything until the server was closed.

Given I cannot reproduce that scenario, I guess this can be closed. Sorry for the inconvenience!

**Comment by beniwohli** [comment]
No worries! It's another datapoint that our current logic is lacking :)
