### ISSUE TITLE
FastAPI / Starlette log shipping to APM Server

### ISSUE THREAD

**Issue by zero0nee** [elastic/apm-agent-python#845]
**Describe the bug**: The FastAPI / Starlette client doesn't seem to be sending data from the python logger to the APM server. I see that `elasticapm.contrib.flask.ElasticAPM` support `logging=True` as an argument, but don't see the same for `elasticapm.contrib.starlette.ElasticAPM`. So I'm not sure if this is a bug or feature request. 

**To Reproduce**

1. Run the FastAPI app specified in `main.py` (see Additional context below).
2. Send requests to the API by running. 
```
for i in $(seq 100); do http :8000/foo foo="${i}@email.domain" bar="${i}"; done
```
3. Check the elasticsearch index pattern `apm-*` if logged data has been added. 
4. Result: Only the message from `apm_client.capture_message('hello, world!')` has been uploaded, but the message from `logger.warning('This is a warning')` was not uploaded. 

**Environment (please complete the following information)**
- OS: OSX
- Python version: 3.8
- Framework and version: fastapi==0.54.1
- APM Server version: 7.7.0
- Agent version: elastic-apm==5.6.0

**Additional context**
This is the code in `main.py`. 
```
from fastapi import Body, FastAPI
from pydantic import BaseModel
from elasticapm.contrib.starlette import make_apm_client, ElasticAPM
from elasticapm.handlers.logging import LoggingFilter, Formatter
import elasticapm

# Parse loggs to be correlated with APM 
# https://www.elastic.co/guide/en/apm/agent/python/master/log-correlation.html
formatter = Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
handler = logging.StreamHandler()
handler.setFormatter(formatter)
handler.addFilter(LoggingFilter())
handler.setLevel(logging.DEBUG)
logger = logging.getLogger("elasticapm")
logger.addHandler(handler)

# Create the fastapi app
app = FastAPI()

# Creating the fastapi apm middleware
# https://www.elastic.co/guide/en/apm/agent/python/master/starlette-support.html
# https://www.elastic.co/guide/en/apm/agent/python/master/configuration.html
settings = {
    'SERVER_URL':os.environ.get('APM_SERVER_URL'),
    'SERVICE_NAME':os.environ.get('APM_SEVICE_NAME'),
    'SECRET_TOKEN':os.environ.get('APM_SECRET_TOKEN'),
    'CAPTURE_BODY':'all',
    'CAPTURE_HEADERS': True,
    'DEBUG': True,
    'COLLECT_LOCAL_VARIABLES':'all',
    'ELASTIC_APM_AUTO_LOG_STACKS':True
    } 
apm_client = make_apm_client(settings)
app.add_middleware(ElasticAPM, client=apm_client)

# Below is a fast API example app
# https://fastapi.tiangolo.com/
class Foo(BaseModel):
    foo: str
    bar: str = None

@app.post("/foo", response_model=Foo)
def foo(request: Foo = Body(...)):
    result = {
        'foo': request.foo,
        'bar': request.bar,
    }
    # Log a message with the root logger
    logger.warning('This is a warning')

    # Log a generic message with capture_message:
    apm_client.capture_message('hello, world!')

    return result
```

**Comment by basepi** [comment]
The FastAPI/Starlette integration does not currently have log shipping support (like the Flask integration does). I think it's something we can add, though! Thanks for opening this issue.

**Comment by zero0nee** [comment]
@basepi Thanks a lot for the quick response. Two follow up questions:
1. When do you think you will be able to add it?
2. Would be more than happy to contribute in adding this feature as well, if you could give me some guidance on where to start? 😄

**Comment by basepi** [comment]
@zero0nee We'd love to have you work on this!

However, I think the direction I'd really like to take this is to add log-shipping as a top-level feature of the agent, rather than continuing to add it to each individual instrumentation/integration. To that end, I need to find some time to crystallize the design of this in my mind a little so I can provide you some good guidance on where to start on adding this as a feature. Stay tuned, I'll revisit this either tomorrow or next week.

**Comment by DanielFerreiraJorge** [comment]
Hi!

I too am really interested in FastAPI on par with flask in terms of features of the apm agent. FastAPI is a really important framework to be left behind. It is not really usable right now...

**Comment by basepi** [comment]
@DanielFerreiraJorge Can you elaborate? What else is the FastAPI support missing besides log shipping?

**Comment by DanielFerreiraJorge** [comment]
@basepi Thanks for the answer! I meant the logging (I do not have enough knowledge about the internals of the agent to know if something else is missing though)

On a side note, the main benefit o FastAPI is the async functionality (besides the typing and autodoc). And the async database access generally comes from the [databases](https://github.com/encode/databases) library. It is really important to have the [asyncpg](https://github.com/MagicStack/asyncpg), which is the driver used for PostgreSQL access, otherwise it will not be possible to trace database calls using FastAPI and PostgreSQL on async applications.

**Comment by basepi** [comment]
Closing in favor of #942.
