### ISSUE TITLE
Disable Exception Reporting

### ISSUE THREAD

**Issue by tybritten** [elastic/apm-agent-python#861]
**Is your feature request related to a problem? Please describe.**
We're using another tool to capture errors (Sentry) and we don't exceptions to also be reported to APM.

**Describe the solution you'd like**
an easy configuration to disable exception handling for APM

**Describe alternatives you've considered**
I'm looking at how to unhook APM from the signals.got_request_exception

**Additional context**
in django i did it this way:
```
from django.core.signals import got_request_exception

             got_request_exception.disconnect(dispatch_uid="elasticapm-exceptions")
```

**Comment by basepi** [comment]
Hello @tybritten! We appreciate the request, but since errors are a pretty core part of our product, I don't think we're going to invest time in removing error reporting. That said, it would be pretty simple to write a [processor](https://www.elastic.co/guide/en/apm/agent/python/current/sanitizing-data.html) to drop the error events.

**Comment by tybritten** [comment]
I understand, and thanks for the tip
